### ISSUE TITLE
unsupported Kubernetes version

### ISSUE THREAD

**Issue by danilofgarcia** [aws-samples/unified-log-aggregation-and-analytics#8]
Hi,

I tried to deploy the solution but I got the error bellow 
Any possible solution for it?

CdkUnifiedLogStack: creating CloudFormation changeset...
CREATE_FAILED        | Custom::AWSCDK-EKS-Cluster                | ekscluster92983EFB
Received response status [FAILED] from custom resource. Message returned: unsupported Kubernetes version

Cloudwatch logs just the same error message.

2e2f4bde-d100-439e-aec3-d0c30a0dae70	ERROR	Invoke Error 	{
    "errorType": "InvalidParameterException",
    "errorMessage": "unsupported Kubernetes version",
    "code": "InvalidParameterException",
    "message": "unsupported Kubernetes version",
    "time": "2022-06-29T21:44:11.878Z",
    "requestId": "b9a0b57d-5d6b-4d81-8650-7cbd2a179f9f",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 56.57791590984764,
    "stack": [
        "InvalidParameterException: unsupported Kubernetes version",
        "    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:52:27)",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:49:8)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)"
    ]
}

**Comment by danilofgarcia** [comment]
Just changed the version in the file "lib/computer/eks.ts" to "version: eks.KubernetesVersion.V1_21" and worked.

**Comment by hariohmprasath** [comment]
Thanks @danilofgarcia. I have updated the kubernetes version in eks.ts file.
